genesis_id = ""
system = "vDice"
icon = "vdice"
dependencies = ["Ethereum"]

[token]
name = "vslice"
symbol = "vSlice"

[consensus]
type = "Ethereum"
algorithm = "Transferable Fungible"

[aliases]
coinmarketcap = "vDice"

[descriptions]
state = "Pre-Public"
system_type = "cryptoasset"
headline = "A Decentralized Gambling Game on Ethereum"
tags = ["DApp"]
twwidid = ""
page_state = "ready"

[crowdsales]
start_date = "2016-11-15T09:00:00"
end_date = "2016-12-15T09:00:00"
genesis_address = ["0x8bCCc9BA2E5706E24a36ddA02ca2A846E39a7bbF"]
funding_terms = "https://blog.vdice.io/wp-content/uploads/2016/10/vDice_ICO_Whitepaper_English.pdf"
funding_url = "http://crowdsale.vdice.io"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""

[specs]

[specs.cap]

[first_price]

[flags]

[[links]]
type = "website"
name = "www.vdice.io"
url = "https://www.vdice.io/"
icon = "website.png"
tags = ["Main"]

[[links]]
type = "blog"
name = "Blog"
url = "https://blog.vdice.io"
icon = "blog.png"
tags = ["Main","News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/vdice_io"
icon = "twitter.png"
tags = ["Main","News"]

[[links]]
type = "forum"
name = "BTT Thread"
url = "https://bitcointalk.org/index.php?topic=1633105.msg16425613#msg16425613"
icon = "forum.png"
tags = ["Main","News"]

[[links]]
type = "reddit"
name = "reddit"
url = "https://reddit.com/r/vdice"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/vDice.io"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "github"
name = "vDice GitHub"
url = "https://github.com/jamesgroton/vDice-Contract-Code"
icon = "github.png"
tags = ["Code"]

[[links]]
type = "paper"
name = "vDice Business Plan"
url = "https://blog.vdice.io/wp-content/uploads/2016/10/vDice_Business_Plan_English.pdf"
icon = "paper.png"
tags = ["Science"]
